name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        id: checkout
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: lobenbergs-gute-weine/firebase-token-generator:latest
